### ISSUE TITLE
HA looses 'sync' or current status of OneControl devices

### ISSUE THREAD

**Issue by JoshWobbles** [rperciaccante/HomeAssistant_OneControl_Discovery#33]
I constantly have issues with HA loosing its sync with the true status of devices in the RV. They display in HA as Unknown and wont show correct status when changed through OneControl and wont allow changing in HA until I open the entity up and change the value there forcing it to be picked up again.

![image](https://user-images.githubusercontent.com/18446288/182885695-6824923e-e74a-45a2-8bc9-2a7bc4ccbc50.png)

**Comment by rperciaccante** [comment]
On your OneControl Monitoring, disconnect the link between "Format Inbound Message" and "Block Repeat Message"
![image](https://user-images.githubusercontent.com/24508878/182978013-e18c6732-fe82-4a1e-b5cd-7eb0957b3143.png)
Another option is to re-deploy the "Block Repeat Messages" node.  I see in your upper right, you are only deploying changed nodes - since the "Block Repeat Messages" node is not re-reployed, it holds the messages it has seen in the past, so it won't change until you change an entity.  

Another option is to add an inject node to the Block Repeat Messages" node with "msg.reset=true" which will flush the blocked messages as well.

**Comment by JoshWobbles** [comment]
Any chances of memory leaks or excessive overhead or other side effects from processing so many more messages?

**Comment by rperciaccante** [comment]
There is always a chance. I disabled it on my install and have not had any issues or any observable change in overhead running on an ODroid....

**Comment by JoshWobbles** [comment]
Seems to be doing the trick, thanks!
